changes.md
config/PhysiCell_settings-backup.xml
core/PhysiCell_standard_models.cpp
sample_projects/template2D/custom_modules/custom.cpp
sample_projects/template3D/custom_modules/custom.cpp

Bug fix to molecular initialization in 2D adn 3D template projects.
SF TIcket 25

bugfix to molec init

---

core/PhysiCell_cell.cpp
core/PhysiCell_cell.h

Functions to make it easier ot do contact testing.
THese use the same testing as the mechanics potential functions.

nearby_cells()

---

core/PhysiCell_cell.cpp

- verify motility enabled flag is present before parsing its value
- fix bug when parsing *multiple* death models

fix cell definition phenotype XML parsing bugs

---

sample_projects/Makefile-default
sample_projects/Makefile-default-bkup
sample_projects/biorobots/Makefile
sample_projects/cancer_biorobots/Makefile
sample_projects/cancer_immune/Makefile
sample_projects/celltypes3/Makefile
sample_projects/heterogeneity/Makefile
sample_projects/pred_prey_farmer/Makefile
sample_projects/template/Makefile
sample_projects/virus_macrophage/Makefile
sample_projects/worm/Makefile

- For all sample_projects, edit Makefiles to also work on Apple M1 (deal with intracellular samples later).

Edit CFLAGS for Apple M1 arm64

---

core/PhysiCell_standard_models.cpp
core/PhysiCell_utilities.cpp

Finished rolling out and testing cell adhesion affinities in the spring function.

almost ready

---

addons/PhysiBoSS/src/maboss_network.h
core/PhysiCell_utilities.cpp
core/PhysiCell_utilities.h

Timestep noise is now following a log-normal distribution.

Change timestep noise in PhysiBoSS

---

addons/PhysiBoSS/src/maboss_intracellular.cpp
addons/PhysiBoSS/src/maboss_intracellular.h
addons/dFBA/src/dfba_intracellular.h
addons/libRoadrunner/src/librr_intracellular.h
core/PhysiCell_cell.cpp
core/PhysiCell_phenotype.h

This adds a new method in the intracellular class : 
void display(std::ostream&os);
Which is then called during the display_cell_definitions(). I implemented it for PhysiBoSS, and wrote dummies for dFBA and libRR.

New display() method on intracellular, to print information during display_cell_definitions()

---

beta/setup_libmaboss.py
beta/setup_libroadrunner.py

* setup_libmaboss.py now provides macOS arm64 version

provide macos arm64

---

core/PhysiCell_cell.cpp

Small fix to move up death flag and linkers to the ingest_cell function

small ingest cell fix

---

beta/test_build_all.sh

* add mechano sample project to build test script

add mechano

---

modules/PhysiCell_pathology.cpp

This fix should solves the problem with comparing SVG output bit by bit.

Added missing whitespace in the SVG code

---

.gitignore

That way the MaBoSS files should never get into the repo or a release

Added MaBoSS installed files to gitignore

---

modules/PhysiCell_MultiCellDS.cpp
modules/PhysiCell_MultiCellDS.h

Support for exporting the list of spring attachments was lacking : here is the implementation.

Added export of spring attachments

---

addons/PhysiMeSS/PhysiMeSS.cpp
sample_projects/physimess/Makefile
sample_projects/physimess/config/Cell_Fibre_Mechanics/mymodel_fibremaze.xml
sample_projects/physimess/config/Cell_Fibre_Mechanics/mymodel_rotating.xml
sample_projects/physimess/config/Fibre_Degradation/mymodel_matrix_degradation.xml
sample_projects/physimess/config/Fibre_Initialisation/mymodel_initialisation.xml
sample_projects/physimess/config/PhysiCell_settings.xml

@elmbeech noticed a few weeks ago that multi-threading in PhysiMeSS was leading to segfaults. 
I guess some work failed to reach the final version of the code, this should fix it. 
Thanks @elmbeech !!!

PhysiMeSS update

---

sample_projects/cancer_immune/custom_modules/cancer_immune_3D.cpp
sample_projects_intracellular/fba/ecoli_acetic_switch/custom_modules/ecoli_acetic_switch.cpp
unit_tests/substrate_internalization/custom_modules/custom.cpp

Update cancer_immune_3D, ecoli_acetic_switch, and substrate_internalization (in unit tests)
Not sure how I missed these in my first sweep through the custom files...

update samples to not need random_seed in userpars

---

core/PhysiCell_cell.cpp
core/PhysiCell_phenotype.h
sample_projects/Makefile-default
sample_projects/custom_division/Makefile
sample_projects/custom_division/config/PhysiCell_settings.xml
sample_projects/custom_division/config/cells.csv
sample_projects/custom_division/custom_modules/custom.cpp
sample_projects/custom_division/custom_modules/custom.h
sample_projects/custom_division/main.cpp

* add a custom `cell_division_function` that, if defined, is invoked at the end of `divide()`
* add a "custom_division" in `sample_projects`

add custom division function

---

.github/workflows/tests.yml
sample_projects_intracellular/boolean/cancer_invasion/config/PhysiCell_settings.xml
sample_projects_intracellular/boolean/template_BM/config/PhysiCell_settings.xml
sample_projects_intracellular/boolean/tutorial/config/cell_cycle/PhysiCell_settings.xml
sample_projects_intracellular/boolean/tutorial/config/cell_cycle/PhysiCell_settings_foxo3_knockout.xml
sample_projects_intracellular/boolean/tutorial/config/cell_cycle/PhysiCell_settings_foxo3_knockout_notebook.xml
sample_projects_intracellular/boolean/tutorial/config/cell_cycle/PhysiCell_settings_notebook.xml
sample_projects_intracellular/boolean/tutorial/config/cell_cycle/PhysiCell_settings_p110_knockin.xml
sample_projects_intracellular/boolean/tutorial/config/cell_cycle/PhysiCell_settings_p110_knockin_notebook.xml
sample_projects_intracellular/boolean/tutorial/config/cell_cycle/PhysiCell_settings_plk1_knockout.xml
sample_projects_intracellular/boolean/tutorial/config/cell_cycle/PhysiCell_settings_plk1_knockout_notebook.xml
sample_projects_intracellular/boolean/tutorial/config/differentiation/PhysiCell_settings.xml
sample_projects_intracellular/boolean/tutorial/config/differentiation/PhysiCell_settings_FOXP3_2_lower.xml
sample_projects_intracellular/boolean/tutorial/config/differentiation/PhysiCell_settings_FOXP3_2_mutant.xml
sample_projects_intracellular/boolean/tutorial/config/differentiation/PhysiCell_settings_NFKB_lower.xml
sample_projects_intracellular/boolean/tutorial/config/differentiation/PhysiCell_settings_NFKB_mutant.xml
sample_projects_intracellular/boolean/tutorial/config/simple_tnf/0_Initial.xml
sample_projects_intracellular/boolean/tutorial/config/simple_tnf/1_Long_TNF.xml
sample_projects_intracellular/boolean/tutorial/config/simple_tnf/1_Long_TNF_stochastic_time.xml
sample_projects_intracellular/boolean/tutorial/config/simple_tnf/2_Short_TNF.xml
sample_projects_intracellular/boolean/tutorial/config/simple_tnf/3_Necrotic_core.xml
sample_projects_intracellular/boolean/tutorial/config/simple_tnf/4_Mutants.xml

Forgot to update the cell rules version in PhysiBoSS models, only one is using it (that I wasn't testing...)

Updated ruleset version in physiboss

---

core/PhysiCell_rules.cpp
core/PhysiCell_utilities.cpp
core/PhysiCell_utilities.h
modules/PhysiCell_geometry.cpp
modules/PhysiCell_settings.cpp

keep the basename the same, i.e. do not change to path/to/output/cells.csv and similarly for substrate ics if they exist
also, remove unreachable lines

copy cell ic file and substrate ic file to output

---

.github/workflows/tests.yml

gh actions deprecation upcoming

remove macos-12 from ci

---

core/PhysiCell_utilities.cpp

write random_seed to output/random_seed.txt

---

sample_projects/asymmetric_division/main.cpp

use new 1.14.1 standard save event triggers in the asymmetric division sample project.

fix event trigger in asym div ex
