MathCancer/PhysiCell

core/PhysiCell_cell.cpp
core/PhysiCell_phenotype.cpp

I changed the random uniform number generator function to use the one provided in PhysiCell_utilities to be consistent with the SeedRandom() function. Otherwise cells with random lifetimes on a single thread use the BioFVM version without specifying a seed, resulting in the same trajectory each time.

updated random number functions

---

sample_projects/biorobots/custom_modules/biorobots.cpp

create_cell_types() was over-writing director_ID and cargo_ID (cell IDs defined in the .h) with corresponding substrate indices. This resulted in incorrect cell colors (no green), among other errors probably.
A good reason for doing automated testing with TravisCI.

fix bug: cell ID vs substrate index

---

core/PhysiCell_cell_container.cpp

Without this check, cells outside of the domain would still produce secretions. 
Since cells outside of the domain have current_voxel_index = -1, this would mean using a negative index to get the voxel for the mesh's voxels vector. 
This would lead to unexpected behaviour, mostly garbage values, and on my system a segfault (still not sure why).

Checking if cell is out of domain before advancing secretion

---

core/PhysiCell_cell_container.h

In the cell container, num_divisions_in_current_step and num_deaths_in_current_step are not initialized.
When activating legacy data output, this will print uninitialized values for the first time point (in log_output function).

Initializing at zero num death and divisions in current step in container

---

.github/workflows/test-macosx.yml
addons/PhysiBoSS/src/maboss_intracellular.cpp
addons/PhysiBoSS/src/maboss_intracellular.h
addons/PhysiBoSS/src/maboss_network.cpp
addons/PhysiBoSS/src/maboss_network.h
beta/setup_libmaboss.py
sample_projects_intracellular/boolean/physiboss_cell_lines/Makefile
sample_projects_intracellular/boolean/physiboss_cell_lines/config/PhysiCell_settings.xml

First update of PhysiBoSS addon to v2.1.0 : 
- Restored stochastic update time, as Gaëlle was originally doing it. Disabled by default, but available via the XML settings.
- Improved error handling
- Updated PhysiBoSS cell lines example to work with latest version of PhysiCell
- Now using libMaBoSS v2.4.1, downloaded directly from the github release
- Improved cleanup of PhysiBoSS folder, not running it every time we do a make clean on the physiboss cell lines project.

Updating PhysiBoSS to 2.1.0

---

addons/PhysiBoSS/src/maboss_intracellular.h
addons/libRoadrunner/src/librr_intracellular.h
core/PhysiCell_cell_container.cpp
core/PhysiCell_phenotype.cpp
core/PhysiCell_phenotype.h
sample_projects_intracellular/boolean/physiboss_cell_lines/custom_modules/custom.cpp
sample_projects_intracellular/boolean/physiboss_cell_lines/custom_modules/custom.h

This pull request changes the way intracellular model updates. 
First, I'm adding a new format for the update function, which is the classic physicell format (Cell*, Phenotype&, double). This allows access to this data during our update function. 
Then, when and how to call it. Historically, PhysiBoSS used to do this in the update_phenotype function, because it could get away with it thanks to intracellular dt > phenotype_dt. Then with libRoadRunner and dFBA, a smaller dt was needed, so Furkan and Miguel implemented it as a call in the main.cpp, calling a function defined in the custom.cpp.
Here the function is now directly called in the update_all_cells, every diffusion_dt. More precisely, it is called if an intracellular model is defined, and if the time has come to update it …

Automatic intracellular update

---

addons/PhysiBoSS/src/maboss_intracellular.cpp
addons/PhysiBoSS/src/maboss_intracellular.h
addons/PhysiBoSS/src/maboss_network.h
addons/PhysiBoSS/src/utils.h
sample_projects_intracellular/boolean/physiboss_cell_lines/config/PhysiCell_settings.xml
sample_projects_intracellular/boolean/physiboss_cell_lines/config/model.cfg
sample_projects_intracellular/boolean/physiboss_cell_lines/custom_modules/custom.cpp

This PR introduces automatic mapping for PhysiBoSS. Through the XML, users can link PhysiCell signals values to PhysiBoSS node states, and PhysiBoSS node states to PhysiCell behaviours.
Ex : 
```
<intracellular type="maboss">
<bnd_filename>./config/model_0.bnd</bnd_filename>
<cfg_filename>./config/model.cfg</cfg_filename>
...
<mapping>
<input name="oxygen" node="A" action="inhibition" threshold="5" inact_threadshold="5" smoothing="0"/>
<output name="apoptosis" node="C" action="activation" value="5" basal_value="0" smoothing="5"/>
</mapping>
</intracellular>
```
In this example, available as a part of the PhysiBoSS cell lines example, the value of the input node A is active when oxygen is below 5 (oxygen is inversely proportional to A : it's an inhibition). A threshold for inactivating the …

Automatic mapping for PhysiBoSS

---

sample_projects_intracellular/boolean/physiboss_cell_lines/Makefile

Here is an updated version of the Makefile to include two fixes : 
- removing mfpmath=both when using macOS arm64 cpus as it causes compatibility issues
- allowing to use PHYSICELL_CPP when recompiling libMaBoSS with make Compile_MaBoSS

Updating Makefile of PhysiBoSS example

---

BioFVM/BioFVM_basic_agent.h
core/PhysiCell_cell.cpp
core/PhysiCell_cell.h
core/PhysiCell_phenotype.cpp
core/PhysiCell_phenotype.h

I had proposed a PR some time ago already around this idea, but then I wasn't sure it was so important and it ended up being closed. 
With the new implementation of PhysiMESS, I wanted to revive it, as I think it will enable things which are not possible otherwise (mostly at destruction), and simplify our life a lot for designing extensions of the Cell class. 
The idea is that for PhysiMESS (and possibly other addons) we need to add new variables to the Cell. We can do this by having our own data structure, like :
```
std::map<Cell*, SomeObject> physimess_cell_object;
```
which is how I defined it for now. And it works, you have to initialize it after cell instantiation, and it's not so bad. But at deletion it's a problem, because we can never clean it at the exact same time as the Cell …

Allowing for derived Cell objects, defined by cell types

---

core/PhysiCell_cell_container.cpp

This PR modifies remove_agent_from_voxel, to actually use the voxel_index used in function's argument. This is needed when an agent span multiple voxels (such as in PhysiMESS). 
In current PhysiCell, this argument is ignored, and the current_mechanics_voxel is queried to know which voxel to remove the agent from. However, in current PhysiCell, this function is always called with the current_mechanics_voxel as argument. So this fix won't have any effect on current PhysiCell, and will allow PhysiCell extension where agents can span multiple voxels.

Really using the given voxel_index in remove_agent_from_voxel

---

BioFVM/BioFVM_vector.cpp
BioFVM/BioFVM_vector.h

There was four operations lacking the const qualifiers on their arguments : 
- axpy and naxpy
- the newly added dot_product and cross_product.

Adding const qualifiers to vectors operations

---

core/PhysiCell_phenotype.h
core/PhysiCell_standard_models.cpp
modules/PhysiCell_pathology.cpp
modules/PhysiCell_pathology.h
sample_projects_intracellular/boolean/physiboss_cell_lines/custom_modules/custom.cpp

For PhysiMeSS, we need new design for our fibers in the svg files (a rectangle). To achieve this, we need to modify both the plotting of the svg plot, and of its legend. 
This PR introduce custom functions for the plotting of the SVG agent and of the agent's legend. The existing functions are now inside standard functions, and are still used automatically. But users now have the choice to choose a different function to plot them, by modifying the function pointer inside the Cell_Functions data structure.

Added custom functions to plot the agent SVG and legend

---

BioFVM/BioFVM_basic_agent.cpp
BioFVM/BioFVM_basic_agent.h

In PhysiMeSS we wanted to have a way to check if the cells are stuck between fibers, so we needed a way to access the value of the velocity computed in update_velocity. 
Since velocity is set back to zero at the end of update_position, but stored in a private variable of Basic_Agent called previous_velocity, we added a const accessor to this variable.

Added const accessor to previous_velocity in Basic_Agent

---

modules/PhysiCell_pathology.cpp
modules/PhysiCell_pathology.h

in PhysiMeSS we wanted to have the distinction between number of fibers and numbers of cells in the count at the top of the SVG. 
So I added an optional parameter in the SVG_plot function, which by default is null and prints the default text (XX agents) in the SVG, but if a function pointer is provided can print something else (XX cells and YY fibers in our case).

Added option to provide a custom function to print the number of agents in SVG

---

modules/PhysiCell_pathology.cpp

Hello Paul!
I have modified the original code for plotting the substrates directly in the SVG:
1) The legend is no longer divided in 13 small rectangles but in 10 (better for proportions in general, even though 13 is a beautiful prime number)
2) Now the legend is compatible with any kind of domain set by the User.

Better legend division and bug fixed when plotting substrate

---

core/PhysiCell_cell.cpp

Hello Paul!
I have added in PhysiCell_cell.cpp an if/else sentence to set to NULL phenotype.intracellular in case one or more cell definitions in the xml have no intracellular module.
Since in the GUI we do not want any inheritance from one cell definition to another, we need to make sure that in mixed models (where some cell types have a maboss model and other ones don't) cell types with no maboss model will not inherit from previous ones, and so phenotype.intracellular will stay == NULL.
I hope this explanation is not too much confusing, otherwise I can try to explain myself better...

Fixed inheritance of intracellular from default dell definition

---

addons/PhysiBoSS/src/maboss_intracellular.h

I just discovered a detail with PhysiBoSS and intracellular models in general : The model keeps running even after cell started dying. 
This was posing a problem with a model with mapping modifying the cell cycle rates (since the cell cycle model is replace by the death model at death).
This might be useful in some cases, so for now I prefer only preventing it in the case of the automatic mapping update of PhysiBoSS.

Checking if the cell is dead before running the PhysiBoSS mapping update

---

addons/PhysiBoSS/src/maboss_intracellular.h

Changelog : 
- PhysiBoSS model no longer updates after cell death
- Cell definitions who don't declare an intracellular model won't automatically inherit the intracellular model of the default cell definition

Bumped PhysiBoSS version to 2.2.1

---

core/PhysiCell_cell.cpp
sample_projects/template/config/PhysiCell_settings.xml

allow for new element at end of `<mechanics>` element that can set the maximum number of attachments. Max num attachments is already a behavior so this is already hooked into the rules grammar.
Minimal working element:
```
<mechanics> 
...
<attachment_rate type="double" units="1/min">0.0</attachment_rate> 
<detachment_rate type="double" units="1/min">0.0</detachment_rate> 
<maximum_number_of_attachments>12</maximum_number_of_attachments>
</mechanics>
```

allow user to change max num (spring) attachments in xml

---

core/PhysiCell_rules.cpp
core/PhysiCell_rules.h

Just needed to initialize the pointers in a better way for them to be passed across functions and objects. I won't pretend to understand why this works, only that it does work.

Fix bug in reading in rules.

---

core/PhysiCell_rules.cpp

In the previous implementation, the last rule determined the maximum or minimum response of the behavior. In the current update, the behavior now checks for the maximum and minimum response in all rules. In cases where the minimum or maximum values do not exist, the system defaults to using the base value.

Fix bug related to maximum/minimum saturation values and uniqueness test for rules

---

BioFVM/BioFVM_matlab.cpp
BioFVM/BioFVM_microenvironment.cpp
BioFVM/BioFVM_microenvironment.h
modules/PhysiCell_settings.cpp

BioFVM substrates can be read in from a .mat file. The .mat file is a single matrix where each row is a voxel. The first three entries in the row are the x-, y-, and z- coordinates, respectively. The remaining columns are the values for ALL substrates.
Checks are made that the number of voxels (rows) is correct, number of substrates (columns - 3) is correct, and that the voxel indices corresponding to the positions in the (x,y,z) columns are all unique.
If the user wants to enable these, then simply go to the microenvironment options in the config xml, enable them, and specify the path to the .mat file relative to the PhysiCell directory.
Errors are issued with reminders about how to correctly set up the .mat file.

added ability to initialize BioFVM substrates with initial conditions

---

core/PhysiCell_signal_behavior.cpp

Add a test for dead cells in the `set_single_behavior` function. This test avoids warning messages when using behaviors to exit cell cycle phases 2 or 3 in rules. Generally, this does not impact other function calls, as we do not need to change the cell cycle rates for dead cells. Note that even when using a rule not applicable to dead cells, the behavior values revert to their prior state (lines [372](https://github.com/MathCancer/PhysiCell/blob/84d033adba4a013f1fb3e7b7ece252ee254a1f26/core/PhysiCell_rules.cpp#L372) and [386](https://github.com/MathCancer/PhysiCell/blob/84d033adba4a013f1fb3e7b7ece252ee254a1f26/core/PhysiCell_rules.cpp#L386) in `PhysiCell_rules.cpp`)

Unnecessary warning message to "exit cycle phase 2 or 3" behaviors

---

core/PhysiCell_cell.cpp

disable_bugfix did not update based on the value of legacy_cell_defaults_copy previously. This fixes that for anyone still using the old, buggy version.

Actually use value of legacy_cell_defaults_copy

---

core/PhysiCell_phenotype.cpp

Working with Arnau on the cell cycle unit test of the multiscale benchmark, we realized that PhysiCell would sometimes have longer cell cycle phases than defined. I tracked it up to this comparison, and I changed it to comparing the absolute value of the difference of the two values to a small number.

Fix elapsed time check to see if cell cycle need to transition

---

modules/PhysiCell_geometry.cpp
modules/PhysiCell_geometry.h
sample_projects/template/config/PhysiCell_settings.xml
sample_projects/template/custom_modules/custom.cpp

A common feature implemented in PhysiCell models is initializing cells within a given cell type with heterogeneity across one or more variables. Currently, users can either set this up in `custom.cpp`--not preferable as it requires C++ knowledge--or by adding columns to `cells.csv` and labeled according to the behavior name (or volume). This latter option, to my knowledge, is not well-known or documented[^1]. It also requires users to use another language to generate the values and to tie the values only to cells read in from a CSV and not any cells placed by other means.
I propose we allow for a new element as a child of `cell_definition` called `initial_parameter_distributions`. Here is a template of what I am currently experimenting with:
```
</custom_data> …
```

Setting initial behaviors from config-defined distributions

---

CITATION.txt
addons/PhysiBoSS/setup_libmaboss.py
addons/PhysiBoSS/src/maboss_intracellular.cpp
addons/PhysiBoSS/src/maboss_intracellular.h
addons/PhysiBoSS/src/maboss_network.cpp
addons/PhysiBoSS/src/utils.h
licenses/MaBoSS.txt
sample_projects_intracellular/boolean/physiboss_cell_lines/Makefile

- Update of the libMaBoSS installation script : Using latest MaBoSS, now in the PhysiBoSS folder.
- Introduced steepness : A parameter controlling the hill coefficient used in the smoothed output mapping. 
- Introduced use_for_dead : A parameter specifying if the mapping is active after cell death. 
- Added PhysiBoSS_DOI and PhysiBoSS_URL, to be used in add_software_citation.
- Updated CITATION.TXT to add PhysiBoSS 2.0 reference.
- Added MaBoSS license in license folder.
- Producing a proper error if BND/CFG file don't exist.
This is what I have for now for the next PhysiCell update. I might add new things before the update happens.

PhysiBoSS 2.2.3 update

---

modules/PhysiCell_SVG.cpp
modules/PhysiCell_SVG.h
modules/PhysiCell_pathology.cpp
modules/PhysiCell_pathology.h
modules/PhysiCell_settings.cpp
modules/PhysiCell_settings.h
sample_projects/interactions/custom_modules/custom.cpp
sample_projects/interactions/custom_modules/custom.h
sample_projects/interactions/main.cpp
sample_projects/physimess/custom_modules/custom.cpp
sample_projects/physimess/custom_modules/custom.h
sample_projects/physimess/main.cpp
sample_projects/template/config/PhysiCell_settings.xml
sample_projects/template/main.cpp

This extends the functionality of plotting substrate heatmaps on SVG output:
* Allows for all colormaps permitted in studio for visualizing substrate concentrations
* Allows for configuration of this heatmap in the XML configuration file
* updates all sample projects so that they can use this functionality just by enabling SVG substrate plots in the XML
To utilize this, open a new project with the herein-modified `template` project and skip to Step 3 below. To make use of this in an existing project, do the following:
1. Add the following line in `main.cpp`. Immediately after defining `cell_coloring_function` works.
```
std::string (*substrate_coloring_function)(double, double, double) = paint_by_density_percentage;
```
2. Replace calls of `SVG_plot` in `main.cpp` with the following. …

Substrate heatmaps in SVGs, defined in config file

---

addons/PhysiBoSS/src/maboss_intracellular.cpp
addons/PhysiBoSS/src/maboss_intracellular.h
modules/PhysiCell_MultiCellDS.cpp
sample_projects_intracellular/boolean/cancer_invasion/main.cpp
sample_projects_intracellular/boolean/physiboss_cell_lines/Makefile
sample_projects_intracellular/boolean/physiboss_cell_lines/main.cpp
sample_projects_intracellular/boolean/template_BM/main.cpp
sample_projects_intracellular/boolean/tutorial/main.cpp

This comes as an effort to make the main.cpp of PhysiBoSS (and ultimately intracellular) models standard. 
As of now, the only difference is that after saving the MultiCellDS data, I'm also saving a CSV PhysiBoSS state file. And if other intracellular models wants to save state, they have to do the same. 
<del>The idea here is to have a wrapper function to include MultiCellDS and intracellular data save, that I called ```save_PhysiCell_Timepoint``` and stored in ```PhysiCell_various_outputs```. </del>
<del>There will have no impact on the rest of PhysiCell, since in this PR only PhysiBoSS Cell Lines example is using this wrapper. But ultimately, it would be nice if all projects would use it, so that we get a standard main.cpp file. </del>
<del>There is no hurry for this, I just wanted to …

Using a unique function to save both MultiCellDS data and intracellular data

---

core/PhysiCell_constants.cpp
core/PhysiCell_constants.h

This may be premature, but would like to at least suggest it get merged in this release. This addresses compiler errors with `PhysiCell_constants{.h,.cpp}` for certain compilers (I had mentioned `clang++` when I need to do serious debugging, and issue https://github.com/MathCancer/PhysiCell/issues/236 mentioned the error on nvc++, as did @clasqui to @vincent-noel for PhysiBoSS). 
I've only tested with the "compile all the sample projects" script. Obviously, it would be good to test with actual simulations (EDIT: see next comment).

fix PhysiCell constants for more compilers

---

core/PhysiCell_utilities.cpp
core/PhysiCell_utilities.h
modules/PhysiCell_settings.cpp
sample_projects/biorobots/custom_modules/custom.cpp
sample_projects/cancer_biorobots/custom_modules/custom.cpp
sample_projects/celltypes3/custom_modules/custom.cpp
sample_projects/heterogeneity/custom_modules/custom.cpp
sample_projects/interactions/custom_modules/custom.cpp
sample_projects/mechano/custom_modules/custom.cpp
sample_projects/physimess/custom_modules/custom.cpp
sample_projects/pred_prey_farmer/custom_modules/custom.cpp
sample_projects/rules_sample/custom_modules/custom.cpp
sample_projects/template/config/PhysiCell_settings.xml
sample_projects/template/custom_modules/custom.cpp
sample_projects/virus_macrophage/custom_modules/custom.cpp
sample_projects/worm/custom_modules/custom.cpp
sample_projects_intracellular/boolean/cancer_invasion/custom_modules/custom.cpp
sample_projects_intracellular/boolean/physiboss_cell_lines/custom_modules/custom.cpp
sample_projects_intracellular/boolean/template_BM/custom_modules/custom.cpp
sample_projects_intracellular/boolean/tutorial/custom_modules/custom.cpp
sample_projects_intracellular/fba/cancer_metabolism/custom_modules/cancer_metabolism.cpp
sample_projects_intracellular/ode/ode_energy/custom_modules/custom.cpp
unit_tests/custom_DCs_2substrates/custom_modules/custom.cpp
unit_tests/custom_DCs_2substrates/custom_modules/custom_v1.cpp
unit_tests/custom_DCs_2substrates/custom_modules/custom_v2.cpp
unit_tests/custom_voxel_values/custom_modules/custom.cpp

allow for node in `<options>` element that contains random seed info. see examples below. As discussed, the template project will continue to support the `random_seed` user parameter and will in fact use this to overwrite the random_seed in options. further remarks:
* `random_seed` intentionally used to match with user parameter to help draw attention for users
* a warning is issued if both are provided that someone other than me may one day see and convince them to keep only the random_seed in options
Random thought: we should write some of the console output to a file to focus attention on warnings that go flying by. also throttle updates on saves based on wall time passed.
```
<options>
...
<random_seed>0</random_seed>
</options>
```
```
<options>
...
<random_seed />
</options>
```
``` …
```

random seed within options

---

BioFVM/BioFVM_microenvironment.cpp
modules/PhysiCell_settings.cpp
modules/PhysiCell_settings.h

Check that each added substrate has a unique name. Same for parameters (for a given type).
Also, clean up some code to improve maintainability/readability.
Suggestion for future improvement: rename some of the many instances of "parameters" in the code. For example, UserParameters has one instance called parameters. Each instance of Parameters has a member called parameters. Many other objects in PhysiCell have parameters members. This makes it hard to track which ones belong where.

Throw error if duplicate substrate or parameter

---

.github/workflows/build_binaries.yml
beta/download_binary.py
beta/setup_windows_dep.py
sample_projects/interactions/Makefile
sample_projects/physimess/Makefile
sample_projects/rules_sample/Makefile
sample_projects/template/Makefile
sample_projects_intracellular/boolean/cancer_invasion/Makefile
sample_projects_intracellular/boolean/physiboss_cell_lines/Makefile
sample_projects_intracellular/boolean/template_BM/Makefile
sample_projects_intracellular/boolean/tutorial/Makefile

This is still very preliminary, but I thought I would send a PR to start discussing it. 
I tried to find a way for users to avoid compilation, and to simply download binaries for a (small) list of projects.  The biggest use case are the template models : That way people can use them and simply use PhysiCell Studio to build their model. 
The binaries are build by GitHub actions, and are stored as release assets for each release. Then for users, they just need to run a python script, which will basically do the equivalent of make <project>; make. Meaning that the binary is ready, the config files are there, and if they want to add custom modules and recompile, it works. This script could later be integrated into PhysiCell Studio.
A few remarks about each OS : 
- On linux, it's relatively …

Script to provide pre-compiled binaries, built by GitHub actions, for linux/mac/windows

---

modules/PhysiCell_pathology.h

anybody can use the substrate coloring on svgs just by editing the config file, i.e. just by using studio. thanks @rheiland for the great suggestion!

set default substrate color fn to give easy access to all projects

---

sample_projects/physimess/config/Fibre_Degradation/mymodel_matrix_degradation.xml

Removing a duplicated parameter which was in one of PhysiMeSS examples

Removing a duplicated parameter which was in one of PhysiMeSS examples

---

core/PhysiCell_utilities.cpp

I want to still default to using the system clock, which means doing that even if it's not set in the options. This will give a more actionable error than if a user removes BOTH the options element and the user parameter.

Fix random seed warning message

---

core/PhysiCell_cell.cpp

Only change target volumes when convert_to_cell_definition is called. This will ensure that cell transformations do not cause instantaneous changes in cell volume.
This is responsive to #283 (except the duplicate `Volume` class bit)

Preserve volume when converting to cell definition

---

.gitignore
Makefile
matlab/read_MultiCellDS_xml.m

Responsive to issue raised in slack re bugs in using the `matlab/read_MultiCellDS_xml.m` script. Perhaps arose due to changes in multicellds output without synching the matlab implementation. see below for details
Bugs handled:
* only one `simplified_data` tag. don't look for another
* `MAT.basic_agents` --> `MAT.cells`
Other changes:
* refactored `matlab/read_MultiCellDS_xml.m` to use local functions
* some renaming of nodes to make more readable
* use `str2double` for efficiency (but really to make matlab not cry)
* eliminate unused variables for efficiency (but also for the not crying thing)
* `== false` --> `~`
* more efficient `setfield` implemented (no matlab, no cry)
* includes `MCDS_constants` in `MCDS.constants`

Fix bug in matlab/read_MultiCellDS_xml.m

---

.github/workflows/build_binaries.yml
beta/download_binary.py

- The binary assets production is not triggered by release[published], not release[created]. Both work when I try to create a release, still unsure why release[created] didn't work for 1.14.0.
- The beta/download_binary.py actually uses a hard-coded release version. So I bumped it to 1.14.1 for PhysiCell. We could add an argument for this in a later version, as well as a "latest" option. But no time today.  
- It was also using sysbio/PhysiBoSS as the default PhysiBoSS repo, I switched it to PhysiBoSS/PhysiBoSS.

Binary production and download fixes

---

core/PhysiCell_cell.cpp

* Add line to preserve internalized substrates after copying the entire phenotype
* Add code to preserve custom data marked as conserved
* store conserved boolean when reading in xml

Preserve internalized substrates and custom data in `Cell::convert_to_cell_definition` function

---

sample_projects/asymmetric_division/config/PhysiCell_settings.xml
sample_projects/asymmetric_division/custom_modules/custom.cpp

Cleanup the use of random_seed in the `asymmetric_division` sample project. This will prevent displaying the "!" warning in the Studio `Config Basics` tab.
* remove it from `user_parameters`
* remove loading it as a user param in custom.cpp

cleanup random_seed

---

core/PhysiCell_rules.cpp

- record the value of applies_to_dead
- use v3 for export (to make sharing easier)

fix bug in export rules

---

core/PhysiCell_standard_models.cpp

- do not let random detachment occur when one cell is attacking another
- this could result in the detachment occuring while the attack continues
- an alternative solution is to say that detachment necessarily ends the attack

disallow random detachment from attack

---

core/PhysiCell_cell.cpp
core/PhysiCell_cell.h

…_neighbors();
update delete_cell(int) and ~Cell() so that if the cell is deleted, it removes itself from all its neighbors' neighbor lists.

bugfix: if cell dies, must remove self from neighbors (to avoid interactions with deleted cells). 

---

modules/PhysiCell_settings.cpp

any path starting with the path separator (indicating an absolute path) will cause an error with the current implementation _even if the path already exists_. This is because it attempts to create a directory with the empty string. This handles checking for that case. It splits on OS to check the path separator. For windows, it checks for the abspath starting with the drive. If we can upgrade to c++17, we could take advantage of `std::filesystem` to greatly simplify this. something like 
```
// Function that we could use if we used c++17
// THIS IS NOT WHAT IS IMPLEMENTED IN THIS PR
bool create_directories(const std::string &path)
{
std::error_code ec;
bool success = std::filesystem::create_directories(path, ec);
if (!success && ec) {
// Handle error or log it, if necessary
return false; …
```

handle abspath for output folder creation

---

modules/PhysiCell_settings.cpp

`stoi` is currently used to parse random seed strings, but it does not work on all `unsigned int`s. So, use `unsigned int` and `stoul` instead to parse the random seed

fix bug reading large random seeds

---

BioFVM/BioFVM_MultiCellDS.cpp
BioFVM/BioFVM_MultiCellDS.h

sidestep issue of overflowing buffer in writing the coordinates to the xmls by using `std::ostringstream`. Note: PhysiBoSS does use this already in `BooleanNetwork.h`

fix buffer bug in writing coords in xml

---

core/PhysiCell_cell.cpp

Previously, it was unset and so it seems one cell (the first placed?) would have an arbitrary value.

initialize total_attack_time to 0.0

---

sample_projects_intracellular/boolean/physiboss_cell_lines/main.cpp

@rheiland caught this today, this is the fix !

Removed call to SeedRandom() in main of physiboss cell lines project

---

.github/workflows/build_binaries.yml
.github/workflows/tests.yml

gh actions deprecation [upcoming](https://github.com/actions/runner-images/issues/10721)
still have macos-14 ci

remove macos-12 from ci

---

modules/PhysiCell_settings.cpp

When creating output directories, currently use `__MINGW32__` and `__MINGW64__` to check if compiling on Windows, but this only checks if using particular windows compilers. they are the ones we tell users to use, but switching to `_W32` will be more robust.

more robust macro to check for windows
